### PR TITLE
Restructured examples to include installation procedure and added automated tests

### PR DESCRIPTION
**Pull request by mark-todd**
Restructure of repo to include install procedure with poetry - add layout for new example structure with tests.

Although currently in it's infancy, the idea would be to move the examples to being a series of automated pytests of a particular implementation of Intersection, that then could be easily migrated to other versions as they are developed.

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
I, personally, like it

**Comment by mark-todd** [comment]
Just an update on this - I've now added an example test based on the draft pep: https://github.com/CarliJoy/intersection_examples/blob/restructure-tests/tests/mypy_test_basic.py

All files that are tested against mypy must have the file format mypy_XXX.py, and are checked against mypy errors using the syntax described here: https://github.com/davidfritzsche/pytest-mypy-testing#writing-mypy-output-test-cases

This allows people to write automated tests that assert particular mypy errors (or pass validly) . I'm also thinking if there's an edge case that isn't currently supported by the version of Intersection in basedmypy, it's valid for the test to fail. The point is that the tests should represent the ideal implementation of Intersection.

**Comment by NeilGirdhar** [comment]
Instead of making testing an optional group, I think you should just put it into the `[tool.poetry.group.dev.dependencies]` section.

**Comment by NeilGirdhar** [comment]
@mark-todd Would it make sense to file issues with based-mypy?

**Pull request merged**
